// File generated by FlutterFire CLI.
// firebase_options.dart — Android is fully configured.
// For other platforms (iOS, web, etc.) run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ Android — fully configured (meditrack-ai-c5d5a)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjwcETN3NYAa4-Jf0cU-jJf_7oD5Pfh_U',
    appId: '1:483958825006:android:91d91ccd82bddb2ee53fbf',
    messagingSenderId: '483958825006',
    projectId: 'meditrack-ai-c5d5a',
    storageBucket: 'meditrack-ai-c5d5a.firebasestorage.app',
  );

  // ✅ Web — configured (meditrack-ai-c5d5a)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqVWkeP4ThlxEThLX2hHlW_R1s5xFDeA',
    appId: '1:483958825006:web:acac1fa48a5ea521e53fbf',
    messagingSenderId: '483958825006',
    projectId: 'meditrack-ai-c5d5a',
    authDomain: 'meditrack-ai-c5d5a.firebaseapp.com',
    storageBucket: 'meditrack-ai-c5d5a.firebasestorage.app',
    measurementId: 'G-PHBLGVBWTQ',
  );

  // ⚠️  iOS — run `flutterfire configure` to get real values
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: 'YOUR-IOS-APP-ID',
    messagingSenderId: '483958825006',
    projectId: 'meditrack-ai-c5d5a',
    storageBucket: 'meditrack-ai-c5d5a.firebasestorage.app',
    iosBundleId: 'com.meditrack.meditrackAi',
  );

  // ⚠️  macOS — run `flutterfire configure` to get real values
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: 'YOUR-MACOS-APP-ID',
    messagingSenderId: '483958825006',
    projectId: 'meditrack-ai-c5d5a',
    storageBucket: 'meditrack-ai-c5d5a.firebasestorage.app',
    iosBundleId: 'com.meditrack.meditrackAi',
  );

  // ⚠️  Windows — run `flutterfire configure` to get real values
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-WINDOWS-API-KEY',
    appId: 'YOUR-WINDOWS-APP-ID',
    messagingSenderId: '483958825006',
    projectId: 'meditrack-ai-c5d5a',
    authDomain: 'meditrack-ai-c5d5a.firebaseapp.com',
    storageBucket: 'meditrack-ai-c5d5a.firebasestorage.app',
  );
}
